name: Gather Crypto Prices

on:
  push: {}
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  run-script:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0

      - name: Set up Deno
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: "1.30.0"

      - name: Set up .env
        run: |
          echo "COINMARKETCAP_API_KEY=${{ secrets.COINMARKETCAP_API_KEY }}" >> .env
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env

      - name: Run mod.ts
        run: |
          deno run --config=deno.jsonc --allow-net --allow-env --allow-write --allow-read mod.ts

      - name: Commit changes
        run: |
          echo "JOB_DATE=$(date +'%H:%M - %B %d, %Y')" >> $GITHUB_ENV

      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: ${{ env.JOB_DATE }}"
          push_options: "--force"
          skip_fetch: true
